### ISSUE TITLE
Update package to 2.0.27

### ISSUE THREAD

**Issue by jeffreytigch** [wget/chocolatey-package-securepointsslvpn#3]
SecurePoint SSL VPN version 2.0.27 came out a month ago. Could you update the package? 

You can see the release here: https://github.com/Securepoint/openvpn-client/releases

**Comment by fraenki** [comment]
@wget Is there anything I could do to help build updates for this packages? Pull requests? Build binaries? Would love to contribute/help. :)

**Comment by fraenki** [comment]
@wget The newest version 2.0.28 fixes another TAP device error. Would love to help get this version into chocolatey and help testing, of course :)

**Comment by wget** [comment]
Package bumped to 2.0.36. =)
